### ISSUE TITLE
Remarks given by client

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/plugin-3P-integration#3]
The client asked
- [x] to separate the name into firstname and lastname. 
- [x] to also store the firstname/lastname/address such that a 2nd incident can be created faster.

I already did both in the message flow, but didn't have time yet to finish this. The caching of the name/phone/etc. didn't work :(

**Comment by RubenMattan** [comment]
step_id is base64 encoded thats why it did not match, also its `rogerthat.user.put()` instead of `rogerthat.user.data.put()`
