### ISSUE TITLE
Comments from client

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/plugin-3P-integration#4]
![screen shot 2018-07-16 at 15](https://user-images.githubusercontent.com/17762105/42763582-c603c22e-8913-11e8-9b70-28fe2f82cb69.png)
![screen shot 2018-07-16 at 15 27 51](https://user-images.githubusercontent.com/17762105/42763591-cbb5ed3c-8913-11e8-8f1e-d21c533e33a4.png)
![screen shot 2018-07-16 at 15](https://user-images.githubusercontent.com/17762105/42763910-9f2fe3a2-8914-11e8-9dcf-bf5377fc561a.png)

**Comment by RubenMattan** [comment]
1a not on our side
1b there are enters in there... where should phone and my address be placed then
1c already resolved

2a what type and urgency should it be then

3a can't do anything about that

4a already resolved
4b not on our side
4c where should we place that email then
4d yes the user receives a message in the app

**Comment by bart-at-mobicage** [comment]
Let's close until we hear something back from our client.
