### ISSUE TITLE
Which role to select for GAE service account?

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/plugin-3P-integration#6]
Can you extend the readme with instructions how to configure? I gave it a try, but have problems with accessing the bucket.

```bash
bart:/tmp/putte$ gcloud auth activate-service-account rogerthat-3p-putte@rogerthat-3p.iam.gserviceaccount.com --key-file  ~/Downloads/rogerthat-3p-putte.json
Activated service account credentials for: [rogerthat-3p-putte@rogerthat-3p.iam.gserviceaccount.com]

bart:/tmp/putte$ echo "" | gsutil cp - gs://rogerthat-3p-putte/reports/__syncing
Your credentials are invalid. Please run
$ gcloud auth login

bart:/tmp/putte$ gsutil -m rsync -r gs://rogerthat-3p-putte/reports .
Your credentials are invalid. Please run
$ gcloud auth login
```

For the other projects I didn't have to execute `gcloud auth login`. Nor did the city ICT'er.

I create the service account with permissions "Storage Object Admin". I tried "Storage Admin" too, activated the service account again, but got the same error message. When I tried the role "GAE Editor", I got `AccessDeniedException: 403 rogerthat-3p-putte@rogerthat-3p.iam.gserviceaccount.com does not have storage.objects.list access to rogerthat-3p-putte.`

<img width="800" alt="screen shot 2018-10-29 at 11 04 13" src="https://user-images.githubusercontent.com/17762105/47643913-0fee6500-db6d-11e8-9faa-a7a60bebb985.png">
<img width="800" alt="screen shot 2018-10-29 at 11 04 36" src="https://user-images.githubusercontent.com/17762105/47643912-0fee6500-db6d-11e8-8ab1-6c85dbb1a8fa.png">

In the mean time I deleted the service account again.

**Comment by lucasvanhalst** [comment]
Perhaps the other buckets their permissions are set to 'public' (so everyone can see the contents). for that you wouldn't need to login indeed.

**Comment by RubenMattan** [comment]
You need to create a service account without any permissions, then go to the bucket and add 'Storage Object Admin' for that service account.
